### ISSUE TITLE
Error in Battle Pets categories

### ISSUE THREAD

**Issue by eTzmNcbkrng** [MonChiSub/Shadowlands-TSM_Group_Setup#1]
Fresh import of these strings causes an error in the `Battle Pet | Caged` and `Battle Pet | Level 25` groups.
I had to go into the TradeSkillMaster.lua file in SavedVars and remove the two lines that referenced a pet with id 161992.

Not sure what this ID was intended to be as it does not exist on this page: https://wowpedia.fandom.com/wiki/BattlePetSpeciesID

**Comment by MonChiSub** [comment]
Believed fixed in new branch which I'll merge once I got all war within items sorted, thanks.
